linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gofmt
    - goimports
    - gocyclo
    - dupl
  disable-all: false

linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  misspell:
    locale: US

run:
  timeout: 5m
  tests: true
